# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos


In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

In [2]:
mainpath = "E:/Curso de Python/Repositorio/python-ml-course/datasets/"
filepath = "ads/Advertising.csv"
data = pd.read_csv(os.path.join(mainpath,filepath))

### Eliminacion de Rasgos Recursiva (Recursive Feauture Elimination)

In [3]:
feauture_cols = ["TV","Radio","Newspaper"]

In [4]:
X = data[feauture_cols] # Variables predictoras
Y = data["Sales"] # Variable a ser predecida

In [5]:
estimator = SVR(kernel = "linear")
selector = RFE(estimator, 2, step = 1)
# RFE (modelo, numero de variables, pasos)
selector = selector.fit(X,Y)

In [6]:
selector.support_

array([ True,  True, False])

In [7]:
selector.ranking_

array([1, 1, 2])

### En el ranking las variables con numero 1 son las mas significativas, despues siguen las menos significativas

### Con from sklearn.linear_model import LinearRegression se puede generar el modelo lineal automaticamente

In [8]:
X_pred = X[["TV","Radio"]]

In [9]:
lm = LinearRegression()
lm.fit(X_pred,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
lm.intercept_

2.921099912405138

In [11]:
lm.coef_

array([0.04575482, 0.18799423])

In [12]:
lm.score(X_pred,Y) # Te da el R^2 Mejorado

0.8971942610828956